### ISSUE TITLE
Enable Sourcegraph

### ISSUE THREAD

**Issue by tigerclawn82** [kandoo/beehive-netctrl#2]
I want to use [Sourcegraph](https://sourcegraph.com) for beehive-netctrl code search, browsing, and usage examples. Can an admin enable Sourcegraph for this repository? Just go to https://sourcegraph.com/github.com/kandoo/beehive-netctrl. (It should only take 30 seconds.)

Thank you!

**Comment by soheilhy** [comment]
Done. :-)
